name: Test Workflow

on:
  push:
    branches: [ main, test-ci-cd-pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Test step
      run: |
        echo "✅ GitHub Actions is working!"
        echo "Branch: ${{ github.ref_name }}"
        echo "Event: ${{ github.event_name }}"
